---
- name: force running handlers now
  meta: flush_handlers

- name: clone or update private git repository
  become: true
  block:
    - name: try to download/update git repo
      ansible.builtin.git:
        repo: "{{ mastodon_scheduler__private_repo }}"
        dest: "{{ _mastodon_scheduler__user.home }}/mastodon-bot"
        version: "{{ mastodon_scheduler__version | default ('main') }}"
        accept_hostkey: true
        update: true
        ssh_opts: "-i {{ _mastodon_scheduler__user.ssh_key_file }}"
  rescue:
    - name: wait until you fixed remote git issues
      pause:
        prompt: "Please fix the issue with your git repository and try again"

    - name: try to download/update git repo again
      ansible.builtin.git:
        repo: "{{ mastodon_scheduler__private_repo }}"
        dest: "{{ _mastodon_scheduler__user.home }}/mastodon-bot"
        version: "{{ mastodon_scheduler__version | default ('main') }}"
        accept_hostkey: true
        update: true
        ssh_opts: "-i {{ _mastodon_scheduler__user.ssh_key_file }}"

- name: "change git repo owner to {{ mastodon_scheduler__user }}"
  become: true
  ansible.builtin.file:
    path: "{{ _mastodon_scheduler__user.home }}/mastodon-bot"
    recurse: true
    owner: "{{ mastodon_scheduler__user }}"
    group: "{{ mastodon_scheduler__group }}"
